version: "3.7"


services:

  nginx:
    image: nginx:latest
    volumes:
      - ./configuration/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./configuration/nginx/ssl:/etc/nginx/ssl:ro
      - ./application/${project_name}:/var/www/html:ro
    ports:
      - "80:80"     # nginx:http
      - "443:443"   # nginx:https
      - "8080:8080" # adminer:http
      - "8025:8025" # mailhog:http
    restart: always
    depends_on:
      - php
      - adminer
      - mailhog
    networks:
      - adminer
      - mailhog
      - nginx

  php:
    build:
      context: ./docker-compose/services/php
      args:
        USER_ID: ${user_id}
        GROUP_ID: ${group_id}
    volumes:
      - ./configuration/supervisor/conf.d/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./application/${project_name}:/var/www/html
    restart: always
    networks:
      - nginx
      - postgresql
      - redis
      - mailhog

  postgresql:
    image: postgres:latest
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${postgres_db}"
      POSTGRES_USER: "${postgres_user}"
      POSTGRES_PASSWORD: "${postgres_password}"
    restart: always
    networks:
      - postgresql
      - adminer

  redis:
    image: redis:latest
    volumes:
      - redis:/data
    restart: always
    networks:
      - redis

  adminer:
    image: adminer:latest
    depends_on:
      - postgresql
    restart: always
    networks:
      - adminer

  mailhog:
    image: mailhog/mailhog
    restart: always
    networks:
      - mailhog


networks:
  nginx:
  postgresql:
  redis:
  adminer:
  mailhog:


volumes:
  postgresql:
  redis:
  adminer:
